### ISSUE TITLE
Data Release Page Tweaks

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#10]
In adding the short blurbs, I realized that we will need to make a few changes to the Data release page.

1.  We will need four columns:
  * Atlas Name
  * Atlas Type
  * Lead Institution(s)
  * Data Release

2.  Can we make the columns sortable?

**Comment by ethansiegl** [comment]
Where do you want this data to be populated from?

**Comment by ecerami** [comment]
Science there are only 12 projects, and they won't change much, I think we can hard-code this.  If you can point me to the page where it's defined, I can modify via pull-request.

**Comment by ethansiegl** [comment]
Content is hardcoded here:
https://github.com/ncihtan/htan-portal/blob/master/components/DataReleasePage.tsx 
@ecerami
