### ISSUE TITLE
Bread crumb tweaks

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#11]
When I go to the data release pages, eg. https://htan-portal-nextjs.now.sh/data/hta3

The bread crumb is hard-coded to something like this:

Home > Data Release > Boston University

Instead of hard-coded, can you use the blurbs instead, e.g. 

Home > Data Release > [content from hta12-short-blurb]

**Comment by ethansiegl** [comment]
I'm not sure I fully understand what you're asking. In most cases, the content is a large paragraph of text which would not fit inside a breadcrumb link.

Are you asking for the title of the page in wordpress to be the breadcrumb link? Or something else? @ecerami

**Comment by ethansiegl** [comment]
pushed fix. should be deployed momentarily
