### ISSUE TITLE
On Atlas Page Remove Tabs that already exist on Explore Page

### ISSUE THREAD

**Issue by inodb** [ncihtan/htan-portal#115]
On this page: https://data.humantumoratlas.org/atlas/hta2. We were previously showing files. We have decided to only list the files on the explore page instead. So when one clicks on the "View Files" button it takes. you to the files page with that atlas selected.

<img width="821" alt="Screen Shot 2021-03-03 at 4 25 29 PM" src="https://user-images.githubusercontent.com/1334004/109874430-1d382480-7c3d-11eb-90fe-0091002b3805.png">

**Comment by adamabeshouse** [comment]
where does the back button take you? @inodb

**Comment by inodb** [comment]
@adamabeshouse back to explore, you get to this page when you are on the atlas page and click on an atlas name
