### ISSUE TITLE
About 200 files (from HTA3) specify parent files which don't exist

### ISSUE THREAD

**Issue by alisman** [ncihtan/htan-portal#131]
These should probably be caught in validation step.  These are the ids of nonexistent files.

["HTA3_8001_7837535366","HTA3_8001_5222399563","HTA3_8001_5548545798","HTA3_8001_6154142702","HTA3_8002_3029856712","HTA3_8002_0107230297","HTA3_8002_1747883314","HTA3_8002_1394371638","HTA3_8002_3338382307","HTA3_8002_1745718508","HTA3_8003_3076428712","HTA3_8003_7305634320","HTA3_8003_0494660791","HTA3_8003_3499345940","HTA3_8003_5962165526","HTA3_8003_0428836996","HTA3_8003_6777845086","HTA3_8003_7901345485","HTA3_8004_0394843352","HTA3_8004_0128439250","HTA3_8004_1150471006","HTA3_8004_1432652420","HTA3_8004_9174607036","HTA3_8004_5022491988","HTA3_8004_3900964761","HTA3_8004_5736174098","HTA3_8004_9195966860","HTA3_8004_9310415618","HTA3_8004_5601203113","HTA3_8004_6705364162","HTA3_8004_1315860394","HTA3_8004_5681119930","HTA3_8004_3087664438","HTA3_8004_0286257566","HTA3_8005_9670386642","HTA3_8005_7369865820","HTA3_8005_1911550239","HTA3_8005_3120423795","HTA3_8005_0757911127","HTA3_8005_3079057174","HTA3_8005_5724194315","HTA3_8005_9613165714","HTA3_8006_8791452259","HTA3_8006_5714587441","HTA3_8006_5649444718","HTA3_8006_2683904382","HTA3_8006_8212174046","HTA3_8006_3417628202","HTA3_8006_4491877044","HTA3_8006_7895825324","HTA3_8001_7837535366","HTA3_8001_5222399563","HTA3_8001_7837535366","HTA3_8001_5222399563","HTA3_8001_7837535366","HTA3_8001_5222399563","HTA3_8001_5548545798","HTA3_8001_6154142702","HTA3_8001_5548545798","HTA3_8001_6154142702","HTA3_8001_5548545798","HTA3_8001_6154142702","HTA3_8002_3029856712","HTA3_8002_0107230297","HTA3_8002_3029856712","HTA3_8002_0107230297","HTA3_8002_3029856712","HTA3_8002_0107230297","HTA3_8002_1747883314","HTA3_8002_1394371638","HTA3_8002_1747883314","HTA3_8002_1394371638","HTA3_8002_1747883314","HTA3_8002_1394371638","HTA3_8002_3338382307","HTA3_8002_1745718508","HTA3_8002_3338382307","HTA3_8002_1745718508","HTA3_8002_3338382307","HTA3_8002_1745718508","HTA3_8003_3076428712","HTA3_8003_7305634320","HTA3_8003_0494660791","HTA3_8003_3499345940","HTA3_8003_3076428712","HTA3_8003_7305634320","HTA3_8003_0494660791","HTA3_8003_3499345940","HTA3_8003_3076428712","HTA3_8003_7305634320","HTA3_8003_0494660791","HTA3_8003_3499345940","HTA3_8003_5962165526","HTA3_8003_0428836996","HTA3_8003_6777845086","HTA3_8003_7901345485","HTA3_8003_5962165526","HTA3_8003_0428836996","HTA3_8003_6777845086","HTA3_8003_7901345485","HTA3_8003_5962165526","HTA3_8003_0428836996","HTA3_8003_6777845086","HTA3_8003_7901345485","HTA3_8004_0394843352","HTA3_8004_0128439250","HTA3_8004_1150471006","HTA3_8004_1432652420","HTA3_8004_0394843352","HTA3_8004_0128439250","HTA3_8004_1150471006","HTA3_8004_1432652420","HTA3_8004_0394843352","HTA3_8004_0128439250","HTA3_8004_1150471006","HTA3_8004_1432652420","HTA3_8004_9174607036","HTA3_8004_5022491988","HTA3_8004_3900964761","HTA3_8004_5736174098","HTA3_8004_9174607036","HTA3_8004_5022491988","HTA3_8004_3900964761","HTA3_8004_5736174098","HTA3_8004_9174607036","HTA3_8004_5022491988","HTA3_8004_3900964761","HTA3_8004_5736174098","HTA3_8004_9195966860","HTA3_8004_9310415618","HTA3_8004_5601203113","HTA3_8004_6705364162","HTA3_8004_9195966860","HTA3_8004_9310415618","HTA3_8004_5601203113","HTA3_8004_6705364162","HTA3_8004_9195966860","HTA3_8004_9310415618","HTA3_8004_5601203113","HTA3_8004_6705364162","HTA3_8004_1315860394","HTA3_8004_5681119930","HTA3_8004_3087664438","HTA3_8004_0286257566","HTA3_8004_1315860394","HTA3_8004_5681119930","HTA3_8004_3087664438","HTA3_8004_0286257566","HTA3_8004_1315860394","HTA3_8004_5681119930","HTA3_8004_3087664438","HTA3_8004_0286257566","HTA3_8005_9670386642","HTA3_8005_7369865820","HTA3_8005_1911550239","HTA3_8005_3120423795","HTA3_8005_9670386642","HTA3_8005_7369865820","HTA3_8005_1911550239","HTA3_8005_3120423795","HTA3_8005_9670386642","HTA3_8005_7369865820","HTA3_8005_1911550239","HTA3_8005_3120423795","HTA3_8005_0757911127","HTA3_8005_3079057174","HTA3_8005_5724194315","HTA3_8005_9613165714","HTA3_8005_0757911127","HTA3_8005_3079057174","HTA3_8005_5724194315","HTA3_8005_9613165714","HTA3_8005_0757911127","HTA3_8005_3079057174","HTA3_8005_5724194315","HTA3_8005_9613165714","HTA3_8006_8791452259","HTA3_8006_5714587441","HTA3_8006_5649444718","HTA3_8006_2683904382","HTA3_8006_8791452259","HTA3_8006_5714587441","HTA3_8006_5649444718","HTA3_8006_2683904382","HTA3_8006_8791452259","HTA3_8006_5714587441","HTA3_8006_5649444718","HTA3_8006_2683904382","HTA3_8006_8212174046","HTA3_8006_3417628202","HTA3_8006_4491877044","HTA3_8006_7895825324","HTA3_8006_8212174046","HTA3_8006_3417628202","HTA3_8006_4491877044","HTA3_8006_7895825324","HTA3_8006_8212174046","HTA3_8006_3417628202","HTA3_8006_4491877044","HTA3_8006_7895825324"]

**Comment by inodb** [comment]
@alisman This has been fixed now I believe. I see these defined in the `syn_data.json` file as level 1:

e.g.:
```
                    {
                        "values": [
                            "ScRNA-seqLevel1",
                            "sc_rna_seq_level_1/xxx.fastq.gz",
                            "HTA3_8001_1002",
                            "HTA3_8001_7837535366",
```
