### ISSUE TITLE
Formatting of Age related attributes

### ISSUE THREAD

**Issue by inodb** [ncihtan/htan-portal#151]
<img width="208" alt="Screen Shot 2021-03-16 at 5 24 31 PM" src="https://user-images.githubusercontent.com/1334004/111381753-7ca22580-867c-11eb-9053-5dde530630ce.png">

Let's convert to years?

**Comment by onursumer** [comment]
@inodb do we still want to see the actual value in days in a tooltip?

**Comment by alisman** [comment]
@inodb looks to me like there's inconsistency.   like, ones in high double digits are good, but the fractions are hard to believe.
![image](https://user-images.githubusercontent.com/186521/112378695-a0d5b600-8cbd-11eb-83e0-662adc7815f5.png)

**Comment by inodb** [comment]
We can assume this is in days. Can show the numbers as rounded in years. Maybe add `(years)` in the header to indicate what the unit is

**Comment by onursumer** [comment]
@inodb These seem to be the suspicious cases. These are most likely either in years or the age is missing/removed.

| HTAN Participant ID | Atlas Name | Age at Diagnosis (in days) |
| --- | --- | --- |
| HTA11_99999965104 | HTAN Vanderbilt | 0 |
| HTA11_347 | HTAN Vanderbilt | 0 |
| HTA11_78 | HTAN Vanderbilt | 0 |
| HTA11_696 | HTAN Vanderbilt | 0 |
| HTA11_83 | HTAN Vanderbilt | 0 |
| HTA11_104 | HTAN Vanderbilt | 0 |
| HTA11_99999965062 | HTAN Vanderbilt | 0 |
| HTA11_411 | HTAN Vanderbilt | 0 |
| HTA11_377 | HTAN Vanderbilt | 0 |
| HTA11_866 | HTAN Vanderbilt | 0 |
| HTA11_392 | HTAN Vanderbilt | 0 |
| HTA11_1391 | HTAN Vanderbilt | 0 |
| HTA11_546 | HTAN Vanderbilt | 0 |
| HTA11_2487 | HTAN Vanderbilt | 0 |
| HTA11_2992 | HTAN Vanderbilt | 0 |
| HTA11_5363 | HTAN Vanderbilt | 0 |
| HTA11_5212 | HTAN Vanderbilt | 0 |
| HTA11_5216 | HTAN Vanderbilt | 0 |
| HTA11_3252 | HTAN Vanderbilt | 0 |
| HTA11_3361 | HTAN Vanderbilt | 0 |
| HTA11_2112 | HTAN Vanderbilt | 0 |
| HTA11_1938 | HTAN Vanderbilt | 0 |
| HTA11_3331 | HTAN Vanderbilt | 0 |
| HTA11_2235 | HTAN Vanderbilt | 0 |
| HTA11_5994 | HTAN Vanderbilt | 0 |
| HTA11_6134 | HTAN Vanderbilt | 0 |
| HTA11_6310 | HTAN Vanderbilt | 0 |
| HTA11_6147 | HTAN Vanderbilt | 0 |
| HTA11_3077 | HTAN Vanderbilt | 0 |
| HTA11_2951 | HTAN Vanderbilt | 0 |
| HTA11_3410 | HTAN Vanderbilt | 0 |
| HTA11_6025 | HTAN Vanderbilt | 0 |
| HTA11_99999970781 | HTAN Vanderbilt | 0 |
| HTA12_1 | HTAN WUSTL | 47 |
| HTA12_10 | HTAN WUSTL | 58 |
| HTA12_2 | HTAN WUSTL | 61 |
| HTA12_15 | HTAN WUSTL | 62 |
| HTA12_4 | HTAN WUSTL | 66 |
| HTA12_9 | HTAN WUSTL | 70 |
| HTA12_16 | HTAN WUSTL | 72 |
| HTA12_3 | HTAN WUSTL | 74 |
| HTA12_11 | HTAN WUSTL | 82 |
