### ISSUE TITLE
Scroll on main page is slow and choppy

### ISSUE THREAD

**Issue by schultzn** [ncihtan/htan-portal#153]
Scrolling is slow and choppy when viewing the different atlases on the main page

https://data.humantumoratlas.org/

**Comment by inodb** [comment]
This is probably slow because the images are big. Both the one at the top and for the atlas pages. We should use smaller images

**Comment by onursumer** [comment]
@inodb Actually this is because of an infinite loop on the home page. I see a constant output in the console. We might be running into an infinite render loop. Need to investigate more.

**Comment by inodb** [comment]
Nice find! That would make sense
