### ISSUE TITLE
Unclear what the download button would do on the cases tab

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#157]
If I click on the cases tab, I see a bunch of cases/research participants, e.g. 

![screenshot_734](https://user-images.githubusercontent.com/1009066/111524410-c2b9c080-8732-11eb-8bc5-6a7bd48683b9.png)

But, what is supposed to happen if I click the Download button here?

Currently, we have clinical data for patients all together in one file, but we also have different tiers of clinical data.  What does download do, or what is it supposed to do?

**Comment by onursumer** [comment]
Hmm, do we really need a download button on this tab?

**Comment by inodb** [comment]
removed this button for now
