### ISSUE TITLE
Do we still need the Atlas tab?

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#158]
This is more of a general question, that probably requires some higher level thinking by @inodb  :-)

But, since the Atlas tab never seems to change do we need this tab for anything?

For example, here I am filtering by WashU, but all the atlases are still there:

![screenshot_735](https://user-images.githubusercontent.com/1009066/111524876-57242300-8733-11eb-99dd-a4c8bc33167b.png)

That seems quite confusing, but maybe we don't even need the tab at all?

**Comment by inodb** [comment]
For this one the idea was to let the global filters update this page. That might help make it more intuitive. I think some atlas listing is still useful. Esp if we extend the listing more in the future like proposed here: https://github.com/ncihtan/htan-portal/issues/161

Some low hanging fruit might be to allow people to easily see all files from one or more atlases directly from this page by e.g. clicking some checkbox and then clicking a "View Files" button which would enable the global atlas filters and take one to the files tab

**Comment by ecerami** [comment]
filtering the atlas tab sounds good.
