### ISSUE TITLE
Use Atlas Name instead of Atlas ID

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#159]
In the file browser, e.g.

![screenshot_736](https://user-images.githubusercontent.com/1009066/111525345-e3364a80-8733-11eb-9bdb-0693f887ebb8.png)

I think we should use Atlas Name, instead of Atlas ID, as most people won't know what the Atlas ID refers to.

**Comment by ecerami** [comment]
Actually, same comment for the other tabs too.

**Comment by onursumer** [comment]
We recently changed `Atlas` to `Atlas ID` per @schultzn's request (see https://github.com/ncihtan/htan-portal/issues/133#issuecomment-794617917). Should we revert it back to Atlas?

**Comment by alisman** [comment]
@onursumer i changed file tab to use htan_name (e.g. HTAN DUKE).   i now see we need to change other tabs as well. i will take care of it.
