### ISSUE TITLE
Translate option?

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#16]
No idea is this can even be fixed.

But, whenever I go to:  https://htan-portal-nextjs.now.sh/standards 

Chrome always thinks this is Norwegian, and asks me if I want to translate!  Is this fixable?

**Comment by ethansiegl** [comment]
I can't reproduce this issue @ecerami

**Comment by ecerami** [comment]
me neither!  seems like the issue has now gone away.  closing.
