### ISSUE TITLE
file format issue

### ISSUE THREAD

**Issue by inodb** [ncihtan/htan-portal#170]
<img width="332" alt="Screen Shot 2021-03-22 at 2 56 51 PM" src="https://user-images.githubusercontent.com/1334004/112043308-e5771b00-8b1e-11eb-9b21-6b5d5ebf6089.png">

biospecimen ids showing up as file formats

**Comment by adamabeshouse** [comment]
Looks like there's an issue in the data - these names are listed in the record location corresponding to `bts:fileFormat` in the `bts:ScRNA-seqLevel1`-schema data.

**Comment by inodb** [comment]
Does indeed seem like the columns in BU are in a different order, which causes the values in `data/syn_data.json` be in a different order for BU. I can look into adjusting the `get_syn_data.py` to handle this if that's the appropriate place to handle it (CC @milen-sage )

**Comment by milen-sage** [comment]
Yes, let's use the schema columns ordering. Can you do on your end @inodb ?

**Comment by inodb** [comment]
Sure!
