### ISSUE TITLE
Explore caching options

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#18]
When I go to various pages on the site, e.g. the home page:  https://htan-portal-nextjs.now.sh/

There is always a little bit of a lag, because we are retrieving content from WP.

Can we only get the content from WP only once an hour and cache the results?  Perhaps, that would speed it up?

**Comment by ecerami** [comment]
Actually, another thought on this.

Right now, the site has a little lag.  But, it's a lot easier to update content and then click refresh to see if it worked.

Ideally, it would be great if content could be cached, but there would be a way to trigger a cache reload, so that author's can see their content load directly.

e.g. https://htan-portal-nextjs.now.sh/?cache=invalidate would load the page, but clear the cache and get new WP content.  something like that.

**Comment by ethansiegl** [comment]
I rewrote the wordpress API calls to happen on the backend so most of the text should appear instantaneously, although page load times will be slightly longer.
