### ISSUE TITLE
Change Atlas Files Tab Download Interaction

### ISSUE THREAD

**Issue by inodb** [ncihtan/htan-portal#193]
- [x] add checkboxes to Atlas Tab (same as https://data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22:%22projectId%22,%22terms%22:%5B%227027adc6-c9c9-46f3-84ee-9badc3a4f53b%22,%2274b6d569-3b11-42ef-b6b1-a0454522b4a0%22%5D%7D%5D), which will update the filters at the top
- [x] Remove links to atlas page
- [x] We need an easy way to download the selection, maybe we can put some button to view files at the top right (same as HCA) or we have another button below the checkboxes that says "View Files"). So basically you select first and then once you click "View Files" it makes the selection and goes to Files tab
- [x] Change order of columns: Atlas Name, Lead Institution, Description

Related to #192

**Comment by alisman** [comment]
@inodb should "car" links oh homepage just link to filtered explore page?
