### ISSUE TITLE
Possible issue with Assay count in Summary

### ISSUE THREAD

**Issue by vthorsson** [ncihtan/htan-portal#211]
Assay counter seems to overcount - 3 assays listed when there is only one for the particular case of HTAPP.  (The data are at 3 *levels*, not sure if that relevant, or just a coincidence)

 
![image](https://user-images.githubusercontent.com/2837859/113438234-051f0680-939d-11eb-9095-4bee4d7a199d.png)

**Comment by inodb** [comment]
Yeah this seems like a bug:

<img width="628" alt="Screen Shot 2021-04-06 at 6 49 51 PM" src="https://user-images.githubusercontent.com/1334004/113787384-ea37f380-9708-11eb-8685-b35b79d59b21.png">
