### ISSUE TITLE
"Imaging" is not an assay

### ISSUE THREAD

**Issue by smrgit** [ncihtan/htan-portal#219]
within the ImagingLevel2 metadata component, there is a field called Imaging_Assay_Type -- this is what should be used in the column with the header "Assay" -- so far we should have images of this type: MxIF, H&E, IMC, mIHC, and CyCIF

**Comment by inodb** [comment]
@onursumer could you help with this one? Basically we would divide up Imaging into those categories listed above ☝️ 

<img width="300" alt="Screen Shot 2021-04-06 at 6 53 17 PM" src="https://user-images.githubusercontent.com/1334004/113787632-60d4f100-9709-11eb-83e3-3de7dceabb62.png">
