### ISSUE TITLE
Clinical Biospecimen Tab

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#23]
When I go here:  https://htan-portal-nextjs.now.sh/atlas/centerA

I see Category 1 in the pull-down menu.

But, this tab should actually contain both clinical data and biospecimen data, e.g. if we use the fake file that Milen created, we should see both Category 1 and Category 2 in the pull-down menu.

**Comment by alisman** [comment]
@ecerami 

In Millen's data, I assume the top level nodes (clinical, biospeciment) correspond to the tabs.  You can see here, clinical has only one category in it.   If in fact these are meant to be conflated in some way, we can do that.  Let me know

![image](https://user-images.githubusercontent.com/186521/78915595-2a16bd00-7a5a-11ea-8fe5-e61a5c5a389f.png)

**Comment by ecerami** [comment]
Hi @alisman yes, the "Clinical Biospecimen" tab is intended to display both clinical data *and* biospecimen categories.
