### ISSUE TITLE
HTAPP scRNAseq Level 3 shows 56 files in the portal, but there are 66 files in the Synapse folder

### ISSUE THREAD

**Issue by elysekozlowski** [ncihtan/htan-portal#232]
<img width="1729" alt="Screen Shot 2021-04-07 at 1 51 36 PM" src="https://user-images.githubusercontent.com/67977813/113911794-62092b00-97a8-11eb-80bd-d19c105bc20e.png">

Synapse folder has 66 files: https://www.synapse.org/#!Synapse:syn24181445

**Comment by inodb** [comment]
We've temporarily removed HTAPP but this has been fixed
