### ISSUE TITLE
dont show columns when there are multiple time points

### ISSUE THREAD

**Issue by inodb** [ncihtan/htan-portal#248]
Can e.g. use OHSU for debugging

<img width="551" alt="Screen Shot 2021-04-13 at 2 15 33 PM" src="https://user-images.githubusercontent.com/1334004/114600792-c1f94900-9c62-11eb-829a-e485fdff23eb.png">

**Comment by onursumer** [comment]
@inodb The problem is that `TumorGrade` is listed twice as a dependency in the jsonld file for `Diagnosis`. That messes up the rendering of the table. Not sure if there are actually multiple time points.
