### ISSUE TITLE
HTAN IDs v. Synapse IDs

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#25]
We currently have two kinds of IDs in HTAN.

HTAN IDs look something like "HTA1", etc.  These are public.  And, also used to create patient IDs, sample IDs, etc.

Synapse IDs look something like:  syn21261141.

Each Atlas will have one HTAN ID and one Synapse ID.

In the My HTAN Atlas feature:

* Can we add a field for HTAN ID? 
* Can we make the links use the HTAN ID (instead of Synapse ID)?  So, for example, when we have a link like:  https://htan-portal-nextjs.now.sh/atlas/centerA, this should be the public HTAN ID, e.g. https://htan-portal-nextjs.now.sh/atlas/hta1

**Comment by alisman** [comment]
yes we can do this

you can add as many custom fields to the Atlas type as you want at the following link:

https://humantumoratlas.org/wp-admin/admin.php?page=pods&action=edit&id=1070

Any field you add will then show up on the atlas edit screen.   This field will of course have to be integrated into the frontend by a developer.

**Comment by ecerami** [comment]
wow, that's neat!  and super easy.  I added HTAN ID and made it required.  Should I keep the issue open regarding the URLs noted above, or should I created a new issue?

**Comment by alisman** [comment]
we can do it in this ticket
