### ISSUE TITLE
Can we add demographics to case tab as well?

### ISSUE THREAD

**Issue by inodb** [ncihtan/htan-portal#253]
Would be nice to be able to see `Demographics` info as well (e.g. Gender). Can we add the columns for this one to the cases tab?

See: https://data.humantumoratlas.org/standard/clinical

**Comment by onursumer** [comment]
@inodb How should we order the columns? `Demographics` before `Diagnosis` or vice versa or something else?

**Comment by inodb** [comment]
@onursumer hmm good question - maybe Diagnosis first for now?

As a side note: it's becoming a lot of columns. Maybe some sort of submenu for columns dropdown makes sense, like:

<img width="343" alt="Screen Shot 2021-04-15 at 1 06 56 PM" src="https://user-images.githubusercontent.com/1334004/114910121-83db6100-9deb-11eb-9614-a0b9de3ee898.png">

So we e.g. have two groups (Diagnosis and Demographics)
