### ISSUE TITLE
Treatment and Clinical Tier 3 missing from standards page

### ISSUE THREAD

**Issue by elysekozlowski** [ncihtan/htan-portal#258]
The Treatment dropdown on the clinical standards page is missing all attributes, and the Clinical Tier 3 is entirely missing.

<img width="1265" alt="Screen Shot 2021-04-16 at 6 41 59 AM" src="https://user-images.githubusercontent.com/67977813/115033075-dade4600-9e7e-11eb-9866-553a0356b9b4.png">

**Comment by onursumer** [comment]
This seems like a data schema issue. `bts:Treatment` does not have any attributes in https://raw.githubusercontent.com/ncihtan/schematic/main/data/schema_org_schemas/HTAN.jsonld. 

Also, there is no id like `bts:ClinicalDataTier3`. Do we have different id(s) for tier 3 attributes?

**Comment by inodb** [comment]
@milen-sage is this one that would be easy to fix in the schema?

**Comment by milen-sage** [comment]
oh Treatment corresponds to Therapy in the schema. Please use Therapy (bts:Therapy) instead of Treatment. That's what the templates use as well.

Clinical Tier 3 is split in separate cancer categories; and we can list them all in the standards pages - here they are:

      {"display_name": "Clinical Tier 3: Acute Lymphoblastic Leukemia", "schema_name": "AcuteLymphoblasticLeukemiaTier3", "type": "clinical"},
      {"display_name": "Clinical Tier 3: Breast Precancer and Cancer ", "schema_name": "BreastCancerTier3", "type": "clinical"},
      {"display_name": "Clinical Tier 3: Colorectal Precancer and Cancer", "schema_name": "ColorectalCancerTier3", "type": "clinical"},
      {"display_name": "Clinical Tier 3: Lung Precancer and Cancer", "schema_name": "LungCancerTier3", "type": "clinical"},
      {"display_name": "Clinical Tier 3: Neuroblastoma and Glioma", "schema_name": "BrainCancerTier3", "type": "clinical"},
      {"display_name": "Clinical Tier 3: Melanoma", "schema_name": "MelanomaTier3", "type": "clinical"},
      {"display_name": "Clinical Tier 3: Ovarian Precancer and Cancer ", "schema_name": "OvarianCancerTier3", "type": "clinical"},
      {"display_name": "Clinical Tier 3: Pancreatic Precancer and Cancer", "schema_name": "PancreaticCancerTier3", "type": "clinical"},
      {"display_name": "Clinical Tier 3: Prostate Precancer and Cancer", "schema_name": "ProstateCancerTier3", "type": "clinical"},
      {"display_name": "Clinical Tier 3: Sarcoma", "schema_name": "SarcomaTier3", "type": "clinical"},
