### ISSUE TITLE
Bulk WES Level 1 appears three times on the standards page

### ISSUE THREAD

**Issue by elysekozlowski** [ncihtan/htan-portal#259]
<img width="1265" alt="Screen Shot 2021-04-16 at 6 46 48 AM" src="https://user-images.githubusercontent.com/67977813/115033694-943d1b80-9e7f-11eb-97dc-4c9df1c71940.png">

**Comment by inodb** [comment]
@onursumer is this an issue in the schema or some issue in the way we are generating these tables on our end?

**Comment by onursumer** [comment]
> @onursumer is this an issue in the schema or some issue in the way we are generating these tables on our end?

@inodb None of the above. It's just a good old copy&paste issue :)

https://github.com/ncihtan/htan-portal/blob/0de63bf963863fdbcfa80ad63275f5f8ce793900/lib/dataSchemaHelpers.ts#L80-L82
