### ISSUE TITLE
Provide more descriptive content for the atlases

### ISSUE THREAD

**Issue by amapeters** [ncihtan/htan-portal#278]
From the explore - Atlas table - under Atlas description, provide a link to sites that have background information about each atlas, or create a page within the HTAN portal with a summary description

**Comment by inodb** [comment]
@amapeters thanks so much for filing this request! How do you like this: https://data.humantumoratlas.org/explore

<img width="318" alt="Screen Shot 2021-05-05 at 12 29 54 PM" src="https://user-images.githubusercontent.com/1334004/117176281-b69ac880-ad9d-11eb-92ad-c2abc071714f.png">

We will probably add an atlas page within the data portal to provide these descriptions as well at some point, but this at least links to the existing descriptions on the main page

**Comment by inodb** [comment]
going to close this for now, but feel free to re-open if this doesn't meet your expectations

**Comment by amapeters** [comment]
That works well. Thanks
