### ISSUE TITLE
Allow the removal of individual filters

### ISSUE THREAD

**Issue by amapeters** [ncihtan/htan-portal#279]
In a query using multiple filters, allow removal of individual ones, not just the whole set

**Comment by inodb** [comment]
@amapeters Thanks for filing your request

Not sure if you saw you can remove individual filters by clicking on them or by deselecting the checkbox in the dropdown?

![deleting_filters](https://user-images.githubusercontent.com/1334004/117181921-bb627b00-ada3-11eb-888d-77e12bbaef08.gif)

**Comment by inodb** [comment]
going to close this for now, but feel free to re-open if you had something else in mind
