### ISSUE TITLE
Sortable Columns in Data Release Table

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#28]
Can we make the Data Release Table sortable by each of the columns.

And, by default, can we sort by Atlas Name?

**Comment by alisman** [comment]
@ethansiegl could you handle this ticket?  Find a react table component that supports sortable columns.   It would be nice if it was bootstrap-style compatible.  Nothing too fancy.

**Comment by ethansiegl** [comment]
PR: https://github.com/ncihtan/htan-portal/pull/29
