### ISSUE TITLE
Add text on Analysis Tools page to indicate these are future enhancements 

### ISSUE THREAD

**Issue by elysekozlowski** [ncihtan/htan-portal#284]
Current Analysis Tools page implies HTAN data is available/soon-to-be available in a variety of tools. We should either add text clearly indicating these are future directions, or hide this page for now.

**Comment by inodb** [comment]
Good point - thanks @elysekozlowski! I updated the tools page: https://data.humantumoratlas.org/tools. Let me know if this works. Feel free to re-open if not
