### ISSUE TITLE
Add text describing what data is currently available

### ISSUE THREAD

**Issue by elysekozlowski** [ncihtan/htan-portal#286]
We should add some brief description of what data is currently available (level 3/4 scRNAseq for now), perhaps on the homepage of the portal

**Comment by inodb** [comment]
@elysekozlowski i put it in the top bar now - does that work?

<img width="1436" alt="Screen Shot 2021-05-11 at 12 50 33 PM" src="https://user-images.githubusercontent.com/1334004/117854565-9bc1cb80-b257-11eb-8856-03fac05017c9.png">


I can change it to state "scRNASeq specifically"
