### ISSUE TITLE
Only list 333 images part of first data release 

### ISSUE THREAD

**Issue by inodb** [ncihtan/htan-portal#291]
Currently we are listing all images, only list the QC'ed images for first data release instead

<img width="323" alt="Screen Shot 2021-05-11 at 11 49 57 AM" src="https://user-images.githubusercontent.com/1334004/117846119-24883980-b24f-11eb-8327-93a9c2de27de.png">

**Comment by vthorsson** [comment]
@inodb , I am not sure if this helps (or if this is already being resolved e.g. by discussion elsewhere)
If portal
excludes Duke (MIBI) images
excludes Vanderbilt MxIF in `mxif_level_2/Registered`
It should (!) be at 333
