### ISSUE TITLE
Long tooltips

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#37]
Some of the tool tips are very long over one line. 

Example:

![screenshot_368](https://user-images.githubusercontent.com/1009066/81091472-51cc3a00-8ecd-11ea-97cb-9ca635f106b1.png)

Can we add line breaks to these, so that they appear on multiple lines and are easier to read?

**Comment by ecerami** [comment]
@alisman this looks to be fixed now.  Can I close?

**Comment by alisman** [comment]
yes

**Comment by ecerami** [comment]
closing
