### ISSUE TITLE
Remove HTAN Biospecimen Google Doc URL

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#38]
In the data.json file https://github.com/ncihtan/htan-portal/blob/master/data/data.json, we currently have:

"description": "HTAN Biospecimen Identifier from which these files were derived [https://docs.google.com/document/d/1podtPP8L1UNvVxx9_c_szlDcU1f8n7bige6XA_GoRVM/edit?usp=sharing]",

Can you please remote the google doc link?

**Comment by ecerami** [comment]
@milen-sage any update on this?

**Comment by milen-sage** [comment]
See PR #53
