### ISSUE TITLE
Options for lots of columns?

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#39]
If I go to:  https://htan-portal-nextjs.now.sh/atlas/hta2

and click on derived data, I see lots of columns when I scroll left.

Are there options for making this more readable?  For example, we only show the first x columns, and then have an option to expand?  or put the table in it's own scroll pane?

**Comment by ethansiegl** [comment]
see https://github.com/ncihtan/htan-portal/pull/50

**Comment by ecerami** [comment]
is this done?  can we close?

**Comment by ethansiegl** [comment]
yes this is merged
