### ISSUE TITLE
Link and Reference HTAN BigQuery resources 

### ISSUE THREAD

**Issue by vthorsson** [ncihtan/htan-portal#420]
Need to alert users to resources available on BigQuery at [ISB-CGC](http://isb-cgc.org) including tables and notebooks. Will do via

- Text on [tools](https://humantumoratlas.org/tools) page
- introduce hyperlinked access in "Viewer" column under Atlas tab
- add links to individual single cell BQ tables under 'View' column of File explorer

 (Content provided here also by  @clarisse-lau )

**Comment by vthorsson** [comment]
Suggested text content for Tools Page

Title: “Google BigQuery”
Description text: “[Google BigQuery](https://cloud.google.com/bigquery) is a massively-parallel analytics engine ideal for working with tabular data.”
Text below image: HTAN single cell and metadata BigQuery tables are available via the CRDC Cancer Gateway in the Cloud: [Explore HTAN BigQuery tables in ISB-CGC](https://isb-cgc.appspot.com/bq_meta_search/). Included are computational notebooks illustrating how to query and work with HTAN data

**Comment by clarisse-lau** [comment]
We've also put together a file mapping single cell file names to ISB-CGC table links, but are unable to attach json files here. Please let us know where to send that

**Comment by vthorsson** [comment]
Possible logos for icons in "View" and "Viewer" columns (Use whatever works best ) 
![10_google-bigquery 0f26b56a8d](https://user-images.githubusercontent.com/2837859/179311011-ba6910b5-061b-45f5-a1f4-0499849ead9d.png)
<img width="182" alt="image" src="https://user-images.githubusercontent.com/2837859/179311013-a1d0046c-de21-400c-993e-32372a080be4.png">

**Comment by inodb** [comment]
Wondering if we want to do something like this as well in the metadata popup:

![Screen Shot 2022-07-21 at 11 57 41 PM](https://user-images.githubusercontent.com/1334004/180359453-940b925e-2003-4392-a12c-42beddde31a5.png)

Trying to figure out where to best point people to the metadata exploration capabilities

**Comment by clarisse-lau** [comment]
Thanks for the suggestion @inodb! That sounds great. 
Since the BQ metadata tables are all combined across centers, maybe for now we can use a more general ISB-CGC link https://isb-cgc.appspot.com/bq_meta_search/isb-cgc-bq.HTAN/ in the popups. 

On our end we'll start brainstorming how best to guide users to obtain only e.g. Biospecimen data from BU, but this can be implemented later

**Comment by vthorsson** [comment]
Thanks for thinking of ways to point to the metadata @inodb !  .  @clarisse-lau has figured out a URL that would be good for this.  (Minor edit : BigQuery instead of Bigquery)

**Comment by inodb** [comment]
@vthorsson @clarisse-lau Thanks for the comments! All of this is live now: https://humantumoratlas.org/explore. Gonna close this ticket 🙌
