### ISSUE TITLE
Improve IDC Linkouts

### ISSUE THREAD

**Issue by inodb** [ncihtan/htan-portal#428]
See feedback from @federov: https://github.com/ncihtan/htan-portal/pull/426#issuecomment-1209510332 and @adamjtaylor https://github.com/ncihtan/htan-portal/pull/426#issuecomment-1210473562

**Comment by aclayton555** [comment]
@inodb something else we should think about is how best to surface the license information applicable to the images (this was raised during our initial conversations with Sage Governance, and documented [HTAN-72](https://sagebionetworks.jira.com/jira/servicedesk/projects/HTAN/queues/custom/1/HTAN-72). My initial thought was that this could be add to the "Download Selected Files" dialogue box, with a tweak to say "Imaging data is available in [DICOM-TIFF format](https://learn.canceridc.dev/dicom/dicom-tiff-dual-personality-files) from the [Imaging Data Commons (IDC)](https://imaging.datacommons.cancer.gov/explore/), and shared under the [CC BY 4.0 license](https://creativecommons.org/licenses/by/4.0/). See the [download instructions](https://learn.canceridc.dev/data/downloading-data)."

Thoughts (cc @adamjtaylor )? The one thing I would want to confirm if whether this would always be CC BY 4.0. I know IDC prefers CC BY 4.0, but I need to confirm with IDC whether data could also be released under any other license.

**Comment by adamjtaylor** [comment]
To follow the terms of the CC BY 4.0 licence we need to give appropriate credit (I think we do this already with the links to the atlases) and link to the licence - In the case of CC BY 4.0: https://creativecommons.org/licenses/by/4.0/

We should absolutely do this on the download page but probably also on the viewer tooltip or in an additional column.

**Comment by aclayton555** [comment]
Closing the loop in this (and closing this issue). We reviewed the licensing information that was added to [this page](https://humantumoratlas.org/data-access) with Sage Governance, and this was deemed suitable.
