### ISSUE TITLE
How to download raw sequencing data

### ISSUE THREAD

**Issue by teng-gao** [ncihtan/htan-portal#457]
Hello,

Having obtained dbGaP access to HTAN controlled access data (phs002371.v2.p1), I've been trying to figure out how to download the raw BAM/FASTQ files for scRNA-seq samples listed on the HTAN portal. First, dbGaP directs me to the CGC portal below:

```
The raw sequencing files for this study are available via the NCI Cancer Data Service (https://cgc.sbgenomics.com/datasets/file-repository). 
```

I check the portal and login, and see that:
<img width="958" alt="image" src="https://user-images.githubusercontent.com/13375875/206029977-cfd9bde4-e219-49cc-bc02-9c24cb86b7b4.png">

Clicking on `explore files` I can browse the BAM/FASTQ files but am unable to download anything.

Could anyone point me to the right way to download these files? Thanks very much.

Best,
Teng

**Comment by aclayton555** [comment]
Hi @teng-gao, thank you for this inquiry and your patience. We have shared this inquiry with the CDS Help Desk to provide clarification on next steps for accessing the data.

Ashley Clayton, on behalf of the HTAN DCC

**Comment by aclayton555** [comment]
Hi @teng-gao the guidance we have received from CDS is for you to reach out to the CDS Help Desk directly to communicate this request. Please contact them via email at [CDSHelpDesk@mail.nih.gov](mailto:CDSHelpDesk@mail.nih.gov).

Ashley Clayton, on behalf of the HTAN DCC
