### ISSUE TITLE
Final data destination is not correct on HTAPP Overview Page 

### ISSUE THREAD

**Issue by vthorsson** [ncihtan/htan-portal#509]
On the [HTAPP Center description page](https://humantumoratlas.org/hta1), the data flow image is incorrect, as it indicates that data is deposited to GDC. 
![HTA1_overview](https://user-images.githubusercontent.com/2837859/236573879-2cd8ee5c-5b90-47ed-8b38-567baa7567ec.png)
This ought to be corrected, and CRDC can be used instead.

**Comment by vthorsson** [comment]
This image , created by Yuriko Mori is more accurate and can be used instead
![HTA1_overview_2023_edit](https://user-images.githubusercontent.com/2837859/236574396-f40a3850-4745-4a41-be5d-5f0a5c7cc4c3.png)

**Comment by vthorsson** [comment]
@inodb are you or someone on your team able to do the image swap? My github connection is broken at the moment and I cannot get a PR in.

**Comment by inodb** [comment]
@vthorsson sure!

**Comment by inodb** [comment]
fixed in https://github.com/ncihtan/htan-portal/commit/903fd323713754b6d3ceb0ef23a7ff7751c3d239
