### ISSUE TITLE
Add download CGC manifest button

### ISSUE THREAD

**Issue by inodb** [ncihtan/htan-portal#513]
Data that's [on CGC](https://humantumoratlas.org/explore?tab=file&selectedFilters=%5B%7B%22value%22%3A%22dbGaP%22%2C%22label%22%3A%22CDS%2FSB-CGC+%28dbGaP+%F0%9F%94%92%29%22%2C%22group%22%3A%22downloadSource%22%2C%22count%22%3A23032%2C%22isSelected%22%3Afalse%7D%5D) is hard to find from the Data Portal:

![image](https://github.com/ncihtan/htan-portal/assets/1334004/e458d675-be4a-4f0c-ae09-694e6fd21c4d)

There is currently not a way to directly link out to this data in the CGC portal, but there is a way to import a manifest. See: https://docs.cancergenomicscloud.org/docs/import-from-a-drs-server#manifest-file-format.

Let's change the current modal to provide a download button that constructs a manifest file in the CGC format. To do so we need:

- [ ] Mapping file from HTAN File ID to CGC UUID

Then we can implement

- [ ] Add modal with download manifest button
- [ ] Text can be something like "To download Level 1/2 sequencing data you first need to request dbGaP access. Afterwards you can import this manifest file into CGC following the instructions [here](https://docs.cancergenomicscloud.org/docs/import-from-a-drs-server#manifest-file-format). "

In a follow up we hope to provide a direct link thru either URL parameters or a POST request, but there were currently some security concerns with that on the CGC side.

**Comment by inodb** [comment]
This is awaiting updates on the CDS side to surface HTAN file IDs

**Comment by clarisse-lau** [comment]
In the future we can use the [CDS Portal ](https://dataservice.datacommons.cancer.gov/#/study/phs002371)to obtain DRS URIs. Currently the portal only contains genomic data, however, I was told that imaging data will be added in March 2024.
