### ISSUE TITLE
Update instructions for downloading IDC data using manifest

### ISSUE THREAD

**Issue by clarisse-lau** [ncihtan/htan-portal#522]
I received the following from a user today:

```
I was trying to download OHSU Cycif data on this webpage 
https://humantumoratlas.org/publications/ohsu_brca_johnson_2022?tab=cycif# 
using Google CLI and s5cmd. I was able to install everything correctly and even 
download the test file as recommended in this document 
https://learn.canceridc.dev/data/downloading-data. 
When I created a manifest to download the above-mentioned dataset it gave me 
the following error :

ERROR "run manifest.txt": "gs://public-datasets-idc/12ec29ba-c37b-42e6-8ea6-1cbbd7469d01.dcm" command (line: 319) not found
```

I believe they thought that list of bucket URLs provided in the popup were the full contents of the manifest.txt file. Perhaps we can clarify in the instructions how the provided URLs should be used? (what is expected in each row of the manifest is a command e.g. `cp s3://public-datasets-idc/ce67894c-eefe-4791-99ac-f7c01c2a6228.dcm .`) Alternatively, we could provide the full commands in the pop up?

Another note, even though `--endpoint-url https://storage.googleapis.com` is specified in the s5cmd command, it appears `s3://` is still expected for the file url ? (the [test command](https://learn.canceridc.dev/data/downloading-data#step-2-download-the-files-defined-by-the-manifest) provided by IDC also uses `s3://` for a Google endpoint)

**Comment by clarisse-lau** [comment]
I'll go ahead and close this as there appears to be a new issue (https://github.com/ncihtan/htan-portal/issues/529) addressing the same items @inodb @onursumer

**Comment by inodb** [comment]
Thanks @clarisse-lau & thanks for reporting before!
