### ISSUE TITLE
Update link to new HTAN Data Ingress docs

### ISSUE THREAD

**Issue by aclayton555** [ncihtan/htan-portal#525]
The roll-out of the new multi-tenant Data Curator App will be complemented by a new link to the HTAN Data Ingress Docs maintained here: https://dca-docs.scrollhelp.site/DCA/Working-version/HTAN/ 

These docs are maintained in Confluence by the FAIR Workstream at Sage, and will incorporated HTAN-specific updates from the HTAN DCC over time. The former docs maintained through Github will be deprecated

For now, we want to ensure that the HTAN Data Portal points users to these new docs from all linked locations. I think these include the following pages:

- [x] https://humantumoratlas.org/transfer

In parallel, Ashley will also update the links to these docs from Synapse.

**Comment by aclayton555** [comment]
@inodb can we prioritize doing this this week? Thanks!

**Comment by inodb** [comment]
Sure!
