### ISSUE TITLE
Suggested manifest.txt file does not work for s5cmd

### ISSUE THREAD

**Issue by onursumer** [ncihtan/htan-portal#529]
Current instructions to create a manifest file for `s5cmd` download seem to be incorrect.

<img width="508" alt="broken_manifest" src="https://github.com/ncihtan/htan-portal/assets/3604198/8d3b2b93-b4e5-41a1-b424-5a520b4938c3">

`gs://...` format does not seem to work with the instructions provided at https://learn.canceridc.dev/data/downloading-data. The correct format should be like

`cp s3://public-datasets-idc/d17ebf63-6551-48fe-bd91-8780ece398dd.dcm .`

EDIT INODB: It looks like this was a recent change (i believe before the example docs showed google cloud cli)

**Comment by fedorov** [comment]
I am sorry about this confusion. Indeed, in IDC we moved away from recommending `gsutil`, since as of [IDC data release 14](https://learn.canceridc.dev/data/data-release-notes#v14-may-2023), IDC data is available both from Google and AWS buckets. Since `gsutil` is a GCP-specific tool that is not expected to work with AWS buckets, and we wanted to reduce confusion and simplify instructions, we switched to recommending `s5cmd`, as discussed in the documentation page referenced above, which works the same way with both GCP and AWS (assuming the correct API endpoint is used).

**Comment by fedorov** [comment]
@inodb we should also discuss and update the way manifest is generated. We moved from file-level to series-level organization (in DICOM, different pyramid levels will be stored as separate files/instances, which belong to the same DICOM series), which will make manifests much shorter. Can you remind me how we did it originally - did we provide manifests for you for each filename, or you did it yourself?

**Comment by inodb** [comment]
@fedorov apologies for the delay - for each file we have several gcs_urls, so e.g. for `HTA9_1_POST_L_RESTAINED_ROI01.ome.tif` with ID `HTA9_1_19378`, our mapping looks like:

```
  "HTA9_1_19378": {
    "HTAN_Parent_Biospecimen_ID": "HTA9_1_48",
    "HTAN_ParticipantID": "HTA9_1",
    "gcs_urls": "[gs://public-datasets-idc/ea400ca0-77ee-4b47-b65f-864b8496ef31.dcm,gs://public-datasets-idc/08bd8c38-15a3-4695-ac67-e82f6bcc88d1.dcm,gs://public-datasets-idc/c61bc7bd-a2ee-48ba-9e1e-38330cad6012.dcm,gs://public-datasets-idc/4af30d2b-4ae1-45d7-9623-8268cbada5d7.dcm,gs://public-datasets-idc/98e38c6f-2c63-4769-865c-8ec4a18a1f82.dcm,gs://public-datasets-idc/6662eb6a-da58-40f2-b749-f39cb6439d3c.dcm,gs://public-datasets-idc/19c21ba5-3d2c-4b43-b1d9-b8267efec9c9.dcm,gs://public-datasets-idc/7a324296-a019-470b-bca5-e3f56d2dfc71.dcm,gs://public-datasets-idc/597f1195-a64f-4e3b-8678-2f626bf86622.dcm,gs://public-datasets-idc/a9fdaf40-af05-4bf4-86e2-2a34f0a8f54f.dcm,gs://public-datasets-idc/c83ed4b0-076a-4977-bdf7-acb3c6705d94.dcm,gs://public-datasets-idc/a752edd1-79f4-42fa-b04f-918b78dbcdef.dcm,gs://public-datasets-idc/8c8084bc-afb1-475b-a213-5ef546a5143c.dcm,gs://public-datasets-idc/d7b396f3-3ebb-432c-b9b1-60ae896b04ed.dcm,gs://public-datasets-idc/503e1092-7097-4416-ac16-b6edc488d132.dcm,gs://public-datasets-idc/e861c544-8bd9-4c94-bf89-230650589d65.dcm,gs://public-datasets-idc/e80cce7c-d78b-4987-bcac-f09798bb2f65.dcm,gs://public-datasets-idc/2e29a850-37a8-4e5d-886a-ba8c670ede48.dcm,gs://public-datasets-idc/482fa38d-f457-4b2e-bd71-bee4c25e2ae9.dcm,gs://public-datasets-idc/427a9c22-8c17-4236-9674-2ce45c3b6875.dcm,gs://public-datasets-idc/2bdcf88c-4202-49ad-93f6-a67dc3bf982a.dcm,gs://public-datasets-idc/fac39d40-5982-46da-b541-7a39ab41fa20.dcm,gs://public-datasets-idc/fd62665d-e376-4f39-844a-03719f23d2fe.dcm,gs://public-datasets-idc/0305660b-6048-456e-ac75-3c73cfbb0109.dcm,gs://public-datasets-idc/21d13f0d-30ee-4590-8916-a2fb42fbd356.dcm,gs://public-datasets-idc/c069ce52-1088-45a3-840f-1b9d9c4fc813.dcm,gs://public-datasets-idc/ba75101f-3216-4faf-bfb3-19c0a9a6ebc5.dcm,gs://public-datasets-idc/5bdd3c70-0df2-4998-a219-6fdba67c3813.dcm,gs://public-datasets-idc/bb902abc-1bb2-4432-890e-2c17756a733d.dcm,gs://public-datasets-idc/b4116229-0db4-4891-8a5a-a4371605f76b.dcm,gs://public-datasets-idc/a9870019-5462-4567-ad40-527394bbe7d6.dcm,gs://public-datasets-idc/fe6e04ff-ca5d-4255-a7c4-4e58f6139fa1.dcm,gs://public-datasets-idc/f3aa103a-dd2f-490a-a5bf-14021dd918ab.dcm,gs://public-datasets-idc/280ed266-0df8-430e-bc85-955acfc0c326.dcm,gs://public-datasets-idc/4129194b-7444-4790-8a38-65c01fd8141f.dcm,gs://public-datasets-idc/d6c1a943-1094-4bad-816f-eb0487e0eba7.dcm,gs://public-datasets-idc/171f2cbb-3222-4f68-acfb-5ba46215c052.dcm,gs://public-datasets-idc/2bf3e6d0-8a75-4558-9968-d8e7bfc3cb70.dcm,gs://public-datasets-idc/82529a69-9cff-444f-8735-3d15145ae6d3.dcm,gs://public-datasets-idc/11c1f574-b7c0-46e4-9b23-8e28027235be.dcm,gs://public-datasets-idc/dcca3228-c9b0-4620-8afc-a79597482d4b.dcm,gs://public-datasets-idc/6d8f32a2-790c-4ae7-a889-4ee4e180470b.dcm,gs://public-datasets-idc/75142912-cd11-476e-9533-1885280226f3.dcm,gs://public-datasets-idc/c25cbc84-cb72-43ff-84a1-6c2aa8b0499f.dcm,gs://public-datasets-idc/c855481d-8acf-46c2-92b0-83b7c146ba69.dcm,gs://public-datasets-idc/b07c6dec-84d9-4254-8824-496fed95f36a.dcm,gs://public-datasets-idc/c0b67cd1-8a44-4d3b-ab86-337245d04d6f.dcm,gs://public-datasets-idc/fef44611-da51-4aa6-abca-a0a788aaba10.dcm,gs://public-datasets-idc/0b43c1a9-0619-4e64-b9e6-e4b2a5c45047.dcm,gs://public-datasets-idc/252d8360-6caa-43fb-8571-26d966734f67.dcm,gs://public-datasets-idc/1b56b0b6-7a02-4f2e-bbe5-6b76e3434e97.dcm,gs://public-datasets-idc/9c5819c1-3932-481c-9ad6-42fc548b139e.dcm,gs://public-datasets-idc/4e36e69a-764d-4e8a-abba-cba3c4bdaacf.dcm,gs://public-datasets-idc/37929d8b-eeb4-4fe4-a4aa-412427aa838a.dcm,gs://public-datasets-idc/de6c376c-eb5b-464f-8f0d-d376f80890b3.dcm,gs://public-datasets-idc/4ed372f4-1254-4656-b94a-6051f54eb874.dcm,gs://public-datasets-idc/1d7ec0bc-3cdd-43c4-8d21-186caaa5c0d3.dcm,gs://public-datasets-idc/ff65c714-03eb-4f4a-b609-9361d29e479e.dcm,gs://public-datasets-idc/b937c6db-04fd-4dd2-a3cd-8c0074997e9e.dcm,gs://public-datasets-idc/60b05d1e-95ba-496f-9e54-15344f7b354c.dcm,gs://public-datasets-idc/64b137f6-8e52-4e7f-aa16-8cf67df51ea4.dcm,gs://public-datasets-idc/2859eab6-086e-471a-a98e-5f8763f149d4.dcm,gs://public-datasets-idc/5a2a7fcb-ce59-4c9d-9287-9f437323928d.dcm,gs://public-datasets-idc/12b7b0cd-b142-4762-8dfa-6221a6298ce6.dcm,gs://public-datasets-idc/5dac5042-839c-4273-ba17-d2e50ddea1dd.dcm,gs://public-datasets-idc/6e1b686d-c060-411b-89e4-26f7f8fa7446.dcm,gs://public-datasets-idc/08c6152e-5604-4b1e-91a5-12426ab0bc39.dcm,gs://public-datasets-idc/68de4831-e980-46c7-9c8e-2118e4f37d3b.dcm,gs://public-datasets-idc/9ff7203c-11f4-4ce3-b114-3cb56cb178d1.dcm,gs://public-datasets-idc/c7650def-397b-4ae3-b2dd-bd66635cb11b.dcm,gs://public-datasets-idc/3917782a-154b-4da7-ba7f-9b60f0d88530.dcm,gs://public-datasets-idc/518081f2-bc75-4063-a6eb-f4154f297825.dcm,gs://public-datasets-idc/6c9e91b3-28a7-42c1-95dc-8edb6010baa5.dcm,gs://public-datasets-idc/bedfd314-9c8e-4097-8cd3-2ca1a55139f0.dcm,gs://public-datasets-idc/43a2a98a-505a-4508-8990-db297639e082.dcm,gs://public-datasets-idc/83eaac0b-0b00-4c99-82be-cab7e898ec1e.dcm,gs://public-datasets-idc/90697fd3-a369-436b-9687-2f6af91bf43e.dcm,gs://public-datasets-idc/14278183-acd7-4aa3-a6b5-1d63f685b6e7.dcm,gs://public-datasets-idc/06bfb142-4147-4256-8fed-39d0491d4e1c.dcm,gs://public-datasets-idc/dce8dd7b-2542-4b84-b043-5b754a2f6000.dcm,gs://public-datasets-idc/48e02c21-3d5b-4143-bef3-1cd4081e2d10.dcm,gs://public-datasets-idc/431f5a79-7976-4a41-9d70-6e98add14aca.dcm,gs://public-datasets-idc/fb9db3f5-bba4-4216-a719-f8e52828be11.dcm,gs://public-datasets-idc/2fc66e15-c65b-4453-99bc-b5c4ffb249a9.dcm,gs://public-datasets-idc/8ef78ebc-1c56-4349-98ae-1615389e1fbf.dcm,gs://public-datasets-idc/f841d461-b5e3-450e-a3f3-a4be2db50107.dcm,gs://public-datasets-idc/b57bf6bc-36f3-4d2e-85a3-e13423ad711a.dcm,gs://public-datasets-idc/8821d33f-10ac-412c-b7b2-49f1ead6ca99.dcm,gs://public-datasets-idc/59879da5-4e42-4039-aec8-4669e55285f5.dcm,gs://public-datasets-idc/abd175c6-d697-4301-9a24-4003bf3c22d5.dcm]",
    "viewer_url": "https://viewer.imaging.datacommons.cancer.gov/slim/studies/2.25.56219147941526607962658668060030231728/series/1.3.6.1.4.1.5962.99.1.2001378817.1491085249.1655563820545.4.0"
  }
```

On our end we still organize everything on the file-level, but I guess each OME TIFF could be represented with one series level  `gcs_url`? Let me know what you recommend - thanks!

**Comment by fedorov** [comment]
> for each file we have several gcs_urls, so e.g. for HTA9_1_POST_L_RESTAINED_ROI01.ome.tif with ID HTA9_1_19378, our mapping looks like:

Can you clarify the semantics of HTA9_1_19378?

After the above is clarified, @dclunie, can you please confirm where that identifier is stored in DICOM so I can write the mapping query? I am not sure I see the answer where I expected to find it: https://github.com/ImagingDataCommons/idc-wsi-conversion#htan.

**Comment by dclunie** [comment]
The various IDs below the patient (participant, case) level should be either in one of the (several) SpecimenIdentifier values in the SpecimenPreparationStepContentItemSequence items or in the ContainerIdentifier in the top level dataset, depending on whether it is the HTAN_Parent_Biospecimen_ID or the HTAN_Data_File_ID from the HTAN metadata spreadsheet.

This particular one (HTA9_1_19378) is the HTAN_Data_File_ID so the easiest place to get it is the ContainerIdentifier (which in DICOM serves as the "slide identifier").

**Comment by inodb** [comment]
Thanks @fedorov and @dclunie ! Correct: `HTA9_1_19378 ` is a `HTAN_Data_File_ID`

An explanation of the ID formats for HTAN can be found here: https://docs.humantumoratlas.org/data_model/identifiers/

**Comment by fedorov** [comment]
@inodb so I looked into this, and the query below can be used to get the AWS and GCP manifests per each Container Identifier (in the respectrive columns of the return table).

```sql
SELECT
  DISTINCT(collection_id),
  ContainerIdentifier,
  CONCAT("s5cmd cp s3",REGEXP_SUBSTR(gcs_url, "(://.*)/"),"/* .") AS s5cmd_manifest_gcp,
  CONCAT("s5cmd cp s3",REGEXP_SUBSTR(aws_url, "(://.*)/"),"/* .") AS s5cmd_manifest_aws
FROM
  `bigquery-public-data.idc_current.dicom_all` AS dicom_all
WHERE
  collection_id LIKE "htan%" and Modality="SM"
ORDER BY
  collection_id ASC
```

Let me know if you want me to run the query and attach the results, or if you need anything else!

There appears to be a single DICOM series for each distinct value of ContainerIdentfier (@dclunie I swear I saw different in the initial query I showed you, but I cannot reproduce it - maybe I had some bug in the query... not sure ... but it looks good now).

For those interested, I recently wrote a post in IDC forum on how to select and download whole slide images from IDC - this way you can read more into how the query above works, and find more slide images beyond HTAN: https://discourse.canceridc.dev/t/how-to-download-whole-slide-microscopy-images-from-idc/461.

**Comment by fedorov** [comment]
> (@dclunie I swear I saw different in the initial query I showed you, but I cannot reproduce it - maybe I had some bug in the query... not sure ... but it looks good now).

I figured it out - I realized my initial query did not limit modality to SM, and so DICOM presentation state series (which are not relevant probably for the HTAN portal users) were included in the result!

**Comment by inodb** [comment]
Thanks @fedorov! That worked! I was able to run the query
