### ISSUE TITLE
Line breaks in Wordpress are not reflected in portal

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#56]
Within wordpress, I have some content like:

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

But, when I go to the data portal, the new lines are ignored and everything is merged into one long paragraph.  See for example:  https://htan-portal-nextjs.now.sh/atlas/hta2

**Comment by inodb** [comment]
I do see line breaks now in the example, so closing this for now. Feel free to re-open
