### ISSUE TITLE
Display level 3 & 4 imaging data using assay type

### ISSUE THREAD

**Issue by clarisse-lau** [ncihtan/htan-portal#575]
Question from Yuriko Mori (NCI) following the HTAN Data jamboree: 
Participants didn’t realize that HTAPP L3/4 MERFISH data are on Portal as they are labeled as Imaging assay data, not MERFISH data. Would it be feasible to somehow make it evident on portal that they are MERFISH data?

**Comment by onursumer** [comment]
Ideally this should be fixed at the data schema level. While level 1 and level 2 have an `Imaging Assay Type` field, level 3 and level 4 don't have this information. (see https://humantumoratlas.org/standard/imaging)

For now I guess we can try deriving it from other fields by improving the data processing step: https://github.com/ncihtan/htan-portal/blob/be420c4232c1543092c6cd35613e0da675afda09/data/processSynapseJSON.ts#L628-L631

Actually we have an `Assay Type` column for raw level 4 imaging data, but this is not part of the Data Schema. Regardless we should be able to use that column value when processing the data.

Things seem tricker for Level 3 imaging data though. The only hint is in the filename. Filenames seem to start with `merfish_level_3/`. We can somehow use the filename to derive the assay type but this may not be very reliable.

**Comment by clarisse-lau** [comment]
Thanks @onursumer. We discussed this a bit at last week's ops call and while adding `Imaging Assay Type` to level 3 and 4 templates would make it straightforward to pull assay information, it would require a large metadata re-submission effort that is probably not feasible, at least not at this time. I also agree that using file or folder names is not reliable. 

Would obtaining assay information through ID linkages be possible? The BigQuery ID Provenance table (`htan-dcc.isb-cgc-bq.id_provenance_current`) in conjunction with Imaging tables could be used for this. For example, a level 3 file which has a level 2 parent annotated with Imaging Assay type = MERFISH would also be displayed under MERFISH.

**Comment by onursumer** [comment]
Hi @clarisse-lau, that should work if we can generate a mapping with BigQuery, and then make it part of the synapse data process script.

I can't seem to query the `htan-dcc.isb-cgc-bq.id_provenance_current` table though. I guess I don't have access to that dataset.

<img width="694" alt="dataset_not_found" src="https://github.com/ncihtan/htan-portal/assets/3604198/3f1ed5a7-e1c6-4ea1-b827-17afd4d5df64">

**Comment by clarisse-lau** [comment]
Sorry @onursumer I gave you the wrong table name! The correct ID is `isb-cgc-bq.HTAN.id_provenance_current`. This table is public, so you should be able to query it

**Comment by onursumer** [comment]
> Sorry @onursumer I gave you the wrong table name! The correct ID is `isb-cgc-bq.HTAN.id_provenance_current`. This table is public, so you should be able to query it

@clarisse-lau This one works. Thanks! Looks like we already fetch and store parent data file IDs for all files. I think we just need to query imaging tables. Do you know if `htan-dcc.combined_assays.ImagingLevel1` and `htan-dcc.combined_assays.ImagingLevel2` tables have all the information we need? There are other datasets (e.g. `htan-dcc.ISB_CGC_r4`) which also have imaging tables. I am not sure which dataset(s) we should use.

**Comment by clarisse-lau** [comment]
Great, ah yeah makes sense that you store parent data file IDs already! 

Yes, please use the `combined_assays` dataset which contains our full internal metadata tables and are updated weekly, e.g. `htan-dcc.combined_assays.ImagingLevel2`

**Comment by onursumer** [comment]
@clarisse-lau There is a preview instance with the updated imaging assay type for level 3 and 4 data at https://htan-portal-nextjs-git-fork-onursumer-fix-imaging-a-d82b94-htan.vercel.app/explore

Could you take a look and let me know if anything is missing/incorrect?

**Comment by clarisse-lau** [comment]
Thanks @onursumer - looks good to me!
