### ISSUE TITLE
Data Standards Pages

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#59]
In the current portal, we have a Data Standards Landing Page:

https://htan-portal-nextjs.now.sh/standards

This links to pages, such as:  https://htan-portal-nextjs.now.sh/standard/cds

This is not as elaborate yet as e.g. https://portal.hubmapconsortium.org/docs/metadata or https://data.humancellatlas.org/metadata

We would like each data standards page to consist of two parts.  Something like this:

![screenshot_477](https://user-images.githubusercontent.com/1009066/87325643-b1634900-c4ff-11ea-9674-8c77143b408a.png)

Tasks:

- [x] Set up JSON-LD page like https://discovery.biothings.io/schema-playground (@milen-sage )
- [x] Add links to JSON-LD page from the data standards page, iframe it in or generate it with next somehow (whatever works easiest)  (@inodb)
- [ ] Add intro documentation for all data types we want to describe (managed by @elysekozlowski  )
- [ ] Make sure language/grammar is consistent across all pages (@elysekozlowski)

**Comment by onursumer** [comment]
We have a brand new Data Standards page now. See #679.
