### ISSUE TITLE
 Improve the UI for mixed data selections

### ISSUE THREAD

**Issue by aclayton555** [ncihtan/htan-portal#632]
This ticket emerges from internal comments on this ticket: https://sagebionetworks.jira.com/browse/HTAN-394

Following our HTAN Data Release 5.1, we now have data types at all levels that may have in different locations. For example there are now Level 2 data that are expected to the access via CDS (e.g. seq, imaging data), and some Level 2 data types (and still L3 and L4 data types) that are expected to be accessed via Synapse (e.g. RPPA).

From Clarisse:

> I think we can refine the logic and move away from explicit level 1/2 vs.. 3/4 behavior. If data has been categorized as Synapse (Open access) per [Update Data Access filtering logic · Issue #620 · ncihtan/htan-portal](https://github.com/ncihtan/htan-portal/issues/620) behavior can be the same for all files regardless of level. 

> So if a user clicks an individual file from the portal, they will be linked out to Synapse, and if they select multiple files to download they’ll be provided with Synapse CLI instructions.

This ticket is to consider potential UI improvements when a user is selecting files for download.

**Comment by onursumer** [comment]
Fixed by #699
