### ISSUE TITLE
500 internal server error for publications

### ISSUE THREAD

**Issue by alexeliotlash** [ncihtan/htan-portal#637]
I'm getting a 500 internal server error when clicking on the publications icons on the explore page.  EG:
https://humantumoratlas.org/publications/hta3_2023_cancer-research_jane-yanagawa

**Comment by onursumer** [comment]
Might be related to this dynamic routing issue on production servers: https://github.com/vercel/next.js/discussions/17498

#638 will hopefully fix it for now. For a better fix we may try to update our next.js version to the latest.

**Comment by alexeliotlash** [comment]
Seems to be working now so closing issue.
