### ISSUE TITLE
don't show external links tab for publications if there are none

### ISSUE THREAD

**Issue by inodb** [ncihtan/htan-portal#641]
see e.g.:

https://humantumoratlas.org/publications/hta3_2023_cancer-research_jane-yanagawa?tab=supporting-links

<img width="1169" alt="image" src="https://github.com/ncihtan/htan-portal/assets/1334004/7b630d36-d261-426b-96aa-a08d7fb26c8c">

**Comment by onursumer** [comment]
Fixed by https://github.com/ncihtan/htan-portal/pull/656/commits/f4c607a911687ef324eb5f1c099aa4403de0ff1d
