### ISSUE TITLE
Add Mass Spectrometry to Data Standards page

### ISSUE THREAD

**Issue by jen-dfci** [ncihtan/htan-portal#680]
Add Mass Spectometry to Data Standards page with level 1-4 + Auxiliary Files.

(Sorry didn't see this earlier with other missing assays.  MD Anderson expects to submit Mass Spec data.)

**Comment by onursumer** [comment]
Hi @jen-dfci, is this going to be a new data standard named `HTAN Mass Spectometry` (similar to the [proteomics](https://humantumoratlas.org/standard/proteomics) we recently added)?

**Comment by onursumer** [comment]
Found a related issue #557

It would be nice if we also had some description to add on top of the page.

**Comment by jen-dfci** [comment]
Yes, I think so.  Currently our Mass Spec standard is for proteomic data.  However, in Phase 2 it sounds like we will also be receiving metabolomic other data via mass spec.  

For description, I just sent a mock up that describes the different levels to Adam and Dave.  Once I get their feedback, I can try to send something to you.  If you are able to get the manifest tables up and running, that would be helpful and perhaps we can add the description later?

**Comment by onursumer** [comment]
@jen-dfci you can preview the new Mass Spectrometry data standard page at https://htan-portal-nextjs-git-fork-onursumer-add-mass-spec-6503df-htan.vercel.app/standard/mass_spectrometry. Let me know if this looks good enough for now.

**Comment by jen-dfci** [comment]
This looks great @onursumer!  Thank you for the fast turn around.  I am still waiting for feedback from Adam and Dave. For top of the page, perhaps we can add the following text and table for now:

Text:
                <p>
                    The current HTAN Mass Spectrometry Standard was developed with a focus on 
                    Proteomics data. The standard may be refined in the future to reflect other data types 
                    such as lipids and metabolites. 
                </p>

Table:
               <table className="table table-data-levels">
                    <thead>
                        <tr>
                            <th>Level</th>
                            <th>Definition</th>
                            <th>Example Data</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>Raw spectral data</td>
                            <td>mz5,dta,ms2,ms1,mzXML,mzML,mzData</td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>Spectrum match peaks</td>
                            <td>Peptide spectrum match (PSM) in csv format</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>Peptide Group information</td>
                            <td>Combined peptide spectrum as csv or tsv files</td>
                        </tr>
                        <tr>
                            <td>4</td>
                            <td>Protein Abundance</td>
                            <td>csv, tsv</td>
                        </tr>
                    </tbody>
                </table>

**Comment by onursumer** [comment]
Thanks @jen-dfci! Just added the text and the table to the top of the page. You can preview at https://htan-portal-nextjs-git-fork-onursumer-add-mass-spec-6503df-htan.vercel.app/standard/mass_spectrometry

**Comment by jen-dfci** [comment]
looks great!  thanks @onursumer!
