### ISSUE TITLE
Data Standards > Spatial Transcriptomics missing some manifests

### ISSUE THREAD

**Issue by jen-dfci** [ncihtan/htan-portal#698]
Spatial Transcriptomics manifests should include (display name listed, schema name in parentheses):
- Slide-seq Level 1 (Slide-seqLevel1)
- Slide-seq Level 2 (Slide-seqLevel2)
- Slide-seq Level 3  (Slide-seqLevel3)
- NanoString GeoMx DSP ROI DCC Segment Annotation Metadata (NanoStringGeoMxDSPROIDCCSegmentAnnotationMetadata)
- NanoString GeoMx DSP ROI RCC Segment Annotation Metadata (NanoStringGeoMxDSPROIRCCSegmentAnnotationMetadata)

A little more difficult: 
MERFISH is submitted with Imaging Level 2 manifest.  Not sure if that can be pulled in as well.

**Comment by onursumer** [comment]
@jen-dfci I added the missing manifests except MERFISH. You can preview at https://htan-portal-nextjs-git-fork-onursumer-add-missing-s-d5d625-htan.vercel.app/standard/spatial_transcriptomics

Adding MERFISH seems tricky without some manual hack.

**Comment by jen-dfci** [comment]
that makes sense.  thank you, @onursumer !
