### ISSUE TITLE
Initial HTAN Data Standards Pages

### ISSUE THREAD

**Issue by ecerami** [ncihtan/htan-portal#7]
Let's add four pages for HTAN data standards, each with content served by WordPress.

The four are:

* Biospecimens
* Clinical
* Single Cell RNASeq
* Imaging

**Comment by ethansiegl** [comment]
Slugs:
data-standards-biospecimsn-blurb content
data-standards-cds-blurb content
data-standards-rnaseq-blurb content
data-standards-imaging-blurb content
