### ISSUE TITLE
New PubMed query for HTAN1 and HTAN2

### ISSUE THREAD

**Issue by alexeliotlash** [ncihtan/htan-portal#718]
Please update the PubMed link on <https://data.humantumoratlas.org/publications>
to the following query to cover both HTAN1 and HTAN2:

(CA233195 OR CA233238 OR CA233243 OR CA233254 OR CA233262 OR CA233280 OR CA233284 OR CA233285 OR CA233291 OR CA233303 OR CA233311 OR CA294459 OR CA294507 OR CA294514 OR CA294518 OR CA294527 OR CA294532 OR CA294536 OR CA294548 OR CA294551 OR CA294552 OR HHSN261201500003I) AND (Achilefu S [LASTAU] OR Ashenberg O [LASTAU] OR Aster J [LASTAU] OR Cerami E [LASTAU] OR Coffey RJ [LASTAU] OR Curtis C [LASTAU] OR Demir E [LASTAU] OR Ding L [LASTAU] OR Dubinett S [LASTAU] Esplin ED [LASTAU] OR Fields R [LASTAU] OR Ford JM [LASTAU] OR Ghosh S [LASTAU] OR Gillanders W [LASTAU] OR Goecks J [LASTAU] OR Gray JW [LASTAU] OR Greenleaf W [LASTAU] OR Guinney J [LASTAU] OR Hanlon SE [LASTAU] OR Hughes SK [LASTAU] OR Hunger SE [LASTAU] OR Hupalowska A [LASTAU] OR Hwang ES [LASTAU] OR Iacobuzio-Donahue CA [LASTAU] OR Jané-Valbuena J [LASTAU] OR Johnson BE [LASTAU] OR Lau KS [LASTAU] OR Lively T [LASTAU] OR Maley C [LASTAU] OR Mazzilli SA [LASTAU] OR Mills GB [LASTAU] OR Nawy T [LASTAU] OR Oberdoerffer P [LASTAU] OR Pe'er D [LASTAU] OR Regev A [LASTAU] OR Rood JE [LASTAU] OR Rozenblatt-Rosen O [LASTAU] OR Santagata S [LASTAU] OR Schapiro D [LASTAU] OR Shalek AK [LASTAU] OR Shrubsole MJ [LASTAU] OR Snyder MP [LASTAU] OR Sorger PK [LASTAU] OR Spira AE [LASTAU] OR Srivastava S [LASTAU] OR Suva M [LASTAU] OR Tan K [LASTAU] OR Thomas GV [LASTAU] OR West RB [LASTAU] OR Williams EH [LASTAU] OR Wold B [LASTAU] OR Bastian B [LASTAU] OR Dos Santos DC [LASTAU] OR Fertig E [LASTAU] OR Chen F [LASTAU] OR Shain AH [LASTAU] OR Ghobrial I [LASTAU] OR Yeh I [LASTAU] OR Amatruda J [LASTAU] OR Spraggins J [LASTAU] OR Brody J [LASTAU] OR Wood L [LASTAU] OR Wang L [LASTAU] OR Cai L [LASTAU] OR Shrubsole M [LASTAU] OR Thomson M [LASTAU] OR Birrer M [LASTAU] OR Xu M [LASTAU] OR Li M [LASTAU] OR Mansfield P [LASTAU] OR Everson R [LASTAU] OR Fan R[LASTAU] OR Sears R[LASTAU] OR Pachynski R [LASTAU] OR Fields R [LASTAU] OR Mok S [LASTAU] OR Ferri-Borgogno S [LASTAU] OR Asgharzadeh S [LASTAU] OR Halene S [LASTAU] OR Hwang TH [LASTAU] OR Ma Z [LASTAU])

Thanks!

**Comment by onursumer** [comment]
![image](https://github.com/user-attachments/assets/be91e02a-4acb-4fce-9ed0-c259842b49b4)

@alexeliotlash I am seeing a warning message for this query. Is this expected?

**Comment by alexeliotlash** [comment]
Yeah. Those are new HTAN2 grant numbers without any publications yet. Just preparing for the future ;-).-AlexOn Nov 26, 2024, at 4:16 PM, Onur Sumer ***@***.***> wrote:﻿
image.png (view on web)
@alexeliotlash I am seeing a warning message for this query. Is this expected?
