### ISSUE TITLE
Add headshot and bio for UCSF Skin atlas bios

### ISSUE THREAD

**Issue by adamjtaylor** [ncihtan/htan-portal#730]
From Hunter

Name: Alan Hunter Shain

> Dr. Shain is an Associate Professor in the Department of Dermatology at the University of California San Francisco (UCSF). He is also affiliated with the Institute of Human Genetics and the Helen Diller Family Comprehensive Cancer Center. He has a B.S. in Biochemistry from the University of Illinois, a Ph.D. in Cancer Biology from Stanford University, and postdoctoral training in Cancer Genomics from UCSF. His laboratory harnesses a wide range of -omic technologies to better understand skin biology. Historically, they have utilized microarray and bulk-cell sequencing technologies, and nowadays they have shifted focus towards single-cell DNA-sequencing, single-cell RNA-sequencing, and spatial transcriptomic technologies.

Headshot:
![image](https://github.com/user-attachments/assets/5742d6f5-5e07-415d-8e6a-4627bedd0c45)

**Comment by adamjtaylor** [comment]
Iwei Yeh, M.D., Ph.D. 
 
Professor of Dermatology and Pathology, UCSF
 
I’m a dermatologist and dermatopathologist with a background in biochemistry, genetics and bioinformatics. I currently practice diagnostic dermatopathology and perform basic and translational research in the field of cutaneous neoplasia. My work has been focused on uncovering the genetics and biology of cutaneous neoplasms and translating our knowledge into clinical practice.

![HeadShot2022-Yeh](https://github.com/user-attachments/assets/135aa375-7726-4ba0-979a-b4b2af77c36c)

**Comment by onursumer** [comment]
Fixed by #729.
See https://humantumoratlas.org/center/hta200.
