### ISSUE TITLE
Write text description for each data standard for standards page

### ISSUE THREAD

**Issue by elysekozlowski** [ncihtan/htan-portal#74]
- [x] write in google docs https://docs.google.com/document/d/1xsjZSW4t2wqOj0a2Xo1pNWUcc0zQ-vxDzudDHoLB8c8/edit?usp=sharing
- [ ] add to wordpress

**Comment by elysekozlowski** [comment]
https://docs.google.com/document/d/1xsjZSW4t2wqOj0a2Xo1pNWUcc0zQ-vxDzudDHoLB8c8/edit?usp=sharing

**Comment by onursumer** [comment]
We have a brand new Data Standards page now. See #679
