### ISSUE TITLE
Wordpress atlas pages are showing up on google

### ISSUE THREAD

**Issue by inodb** [ncihtan/htan-portal#86]
Need to figure out some way to avoid google from indexing them

<img width="792" alt="Screen Shot 2021-02-02 at 1 22 47 PM" src="https://user-images.githubusercontent.com/1334004/106644987-cb2ab300-6559-11eb-8b79-d9e0bad11678.png">

**Comment by alisman** [comment]
@alisman i installed an SEO plugin that allows us to set no-index meta tag on per post basis.   You have to go through each atlas and tag them as such.  I did that for existing 12 atlases.
